In [1]:
import pandas as pd

# Pegar dados do Enade de Ciência da Computação na UNIFOR

In [3]:
course_codes = pd.read_csv('../data/MICRODADOS_CADASTRO_CURSOS_2021.csv', encoding='ISO-8859-1', sep=';')
universities = pd.read_csv('../data/MICRODADOS_CADASTRO_IES_2021.CSV', encoding='ISO-8859-1', sep=';')
courses = pd.merge(course_codes, universities, on='CO_IES')
courses[['CO_IES', 'SG_IES', 'NO_IES', 'NO_CURSO', 'CO_CURSO']]

C:\Users\ajoao\AppData\Local\Temp\ipykernel_21160\331067483.py:1: DtypeWarning: Columns (1: NO_REGIAO, 3: NO_UF, 4: SG_UF, 6: NO_MUNICIPIO) have mixed types. Specify dtype option on import or set low_memory=False.
  course_codes = pd.read_csv('../data/MICRODADOS_CADASTRO_CURSOS_2021.csv', encoding='ISO-8859-1', sep=';')

,CO_IES,SG_IES,NO_IES,NO_CURSO,CO_CURSO
0,1,UFMT,UNIVERSIDADE FEDERAL DE MATO GROSSO,Administração Pública,1113617
1,1,UFMT,UNIVERSIDADE FEDERAL DE MATO GROSSO,Ciências Naturais E Matemática,114386
2,1,UFMT,UNIVERSIDADE FEDERAL DE MATO GROSSO,Matemática,1357965
3,1,UFMT,UNIVERSIDADE FEDERAL DE MATO GROSSO,Pedagogia,105652
4,1,UFMT,UNIVERSIDADE FEDERAL DE MATO GROSSO,Tecnologia Educacional,1425400
...,...,...,...,...,...
444781,953,UNIMES,UNIVERSIDADE METROPOLITANA DE SANTOS,Gestão Pública,1268553
444782,953,UNIMES,UNIVERSIDADE METROPOLITANA DE SANTOS,Letras - Língua Portuguesa,1357716
444783,953,UNIMES,UNIVERSIDADE METROPOLITANA DE SANTOS,Matemática,100724
444784,953,UNIMES,UNIVERSIDADE METROPOLITANA DE SANTOS,Música,1190335
444785,953,UNIMES,UNIVERSIDADE METROPOLITANA DE SANTOS,Pedagogia,96655

In [4]:
UNIFOR_CO = courses[courses['SG_IES'] == 'UNIFOR']['CO_IES'].values[0]

f'Código da UNIFOR é {UNIFOR_CO}'

'Código da UNIFOR é 555'

In [6]:
courses_in_unifor = courses[courses['CO_IES'] == UNIFOR_CO]
courses_in_unifor[['NO_CURSO', 'CO_CURSO']]

                                            NO_CURSO  CO_CURSO
2696                                   Administração   1572759
2697           Análise E Desenvolvimento De Sistemas   1575331
2698                              Ciências Contábeis   1572766
2699                               Gestão Financeira   1568178
2700                               Marketing Digital   1571354
80442                          Abi - Educação Física   5001676
80443                                  Administração     11721
80444          Análise E Desenvolvimento De Sistemas   1172346
80445                        Arquitetura E Urbanismo     18324
80446                           Cinema E Audiovisual    113088
80447                          Ciência Da Computação     11730
80448                             Ciências Contábeis     11723
80449                            Ciências Econômicas     11722
80450  Comunicação Social - Publicidade E Propaganda     39387
80451                              Comércio Exterior     39845
80452                                 Design De Moda   1261765
80453                                        Direito     11726
80454                                Educação Física     11717
80455                                Educação Física    311717
80456                            Energias Renováveis   1205275
80457                                     Enfermagem     11719
80458               Engenharia Ambiental E Sanitária    107686
80459                               Engenharia Civil     11714
80460                       Engenharia De Computação    107689
80461             Engenharia De Controle E Automação     40095
80462                         Engenharia De Produção     40071
80463                 Engenharia De Telecomunicações     40413
80464                          Engenharia Eletrônica     41729
80465                            Engenharia Elétrica     41723
80466                            Engenharia Mecânica     11715
80467                           Estética E Cosmética   1315325
80468                                        Eventos   1172342
80469                                       Farmácia     18325
80470                                   Fisioterapia     11718
80471                                 Fonoaudiologia     11727
80472                                     Jornalismo     39388
80473                                      Marketing   1172340
80474                                       Medicina     93001
80475                           Medicina Veterinária   1357703
80476                                       Nutrição     56630
80477                                    Odontologia     11731
80478                                     Psicologia     35443
81619                                  Administração   1572759
81620          Análise E Desenvolvimento De Sistemas   1575331
81621                             Ciências Contábeis   1572766
81622                              Gestão Financeira   1568178
81623                              Marketing Digital   1571354

In [8]:
computer_science_like = courses_in_unifor['NO_CURSO'].str.contains('da computa', case=False, na=False)
result = courses_in_unifor[computer_science_like][['NO_CURSO', 'CO_CURSO']]

COMPUTER_SCIENCE_CODE = result['CO_CURSO'].values[0]
print(f'O código do curso de Ciência da Computação na UNIFOR é {COMPUTER_SCIENCE_CODE}')

result

O código do curso de Ciência da Computação na UNIFOR é 11730

                    NO_CURSO  CO_CURSO
80447  Ciência Da Computação     11730